#!/bin/sh

export XAPPLRESDIR=$HOME/.app-defaults
#export GTK_MODULES=$GTK_MODULES:globalmenu-gnome
xcompmgr -n &
echo configuring keyboard
setxkbmap -model pc101
xmodmap $HOME/Development/RCs/xmodmap

